### ISSUE TITLE
Viewport restrictions create bizarre behavior in horizontal scrolling websites

### ISSUE THREAD

**Issue by jacobh0** [vadikom/poshytip#6]
Just wanted to let you know that the restrictions on keeping the tooltip in the viewport create bizarre behavior on horizontal scrolling websites.

The viewport size on the initial pageload is the boundary evidently, and if you have a tooltip outside of it, then it is skewed to the left as if being restricted.

**Comment by jacobh0** [comment]
My options:

``` javascript
  $('a.photo[title]').poshytip({
    className: 'tip-twitter',
    followCursor: true,
    alignX: 'center',
    slide: false
  });
```

**Comment by jacobh0** [comment]
Turns out to be more of a styling problem with the CSS, changed to this and it mostly fixes the problem:

``` css
.tip-twitter {
    opacity:0.8;
    z-index:1000;
}
.tip-twitter .tip-inner {
    font:bold 11px 'Lucida Grande',sans-serif;
    padding:8px 8px;
    color:#fff;
    text-align:left;
    background-color:#000;
    border-radius:4px;
    -moz-border-radius:4px;
    -webkit-border-radius:4px;
}
```

However the arrow positioning is still off
